import Letter from "./Letter";

export default function Tab({ hasło, setHasło, hasło1 }) {
  return (
    <div className="Tab">
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        A
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        Ą
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        B
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        C
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        Ć
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        D
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        E
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        Ę
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        F
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        G
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        H
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        I
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        J
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        K
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        L
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        Ł
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        M
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        N
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        Ń
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        O
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        Ó
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        P
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        Q
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        R
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        S
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        Ś
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        T
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        U
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        W
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        V
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        X
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        Y
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        Z
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        Ź
      </Letter>
      <Letter
        hasło={hasło}
        hasło1={hasło1}
        setHasło={setHasło}
        className="Letter"
      >
        Ż
      </Letter>
    </div>
  );
}
