export const categories = {
  movies: [
    "PULP FICTION",
    "SKAZANI NA SHAWSHANK",
    "LISTY DO M",
    "KAC VEGAS",
    "HARRY POTTER",
    "PIĘKNA I BESTIA",
    "NIENAWISTNA ÓSEMKA",
  ],
  games: [
    "WIEDŹMIN",
    "CYBERPUNK",
    "FIFA",
    "NEED FOR SPEED",
    "CALL OF DUTY",
    "ASSASSINS CREED",
    "GRAND THEFT AUTO",
    "SKYRIM",
    "RED DEAD REDEMPTION",
  ],
  food: [
    "HOT DOG",
    "HAMBURGER",
    "PIEROGI",
    "NALEŚNIKI",
    "BIGOS",
    "ZAPIEKANKA",
    "KEBAB",
    "FRYTKI",
    "BARSZCZ",
  ],
};
